from typing import Protocol
from uuid import UUID

from collaboration.domain.entities import CrdtSnapshot, CrdtUpdate


class CrdtStorageRepository(Protocol):
    async def get_latest_snapshot(self, document_id: UUID) -> CrdtSnapshot | None: ...

    async def get_updates_since(self, document_id: UUID, since_seq: int) -> list[CrdtUpdate]: ...

    async def save_update(self, update: CrdtUpdate) -> CrdtUpdate: ...

    async def save_snapshot(self, snapshot: CrdtSnapshot) -> CrdtSnapshot: ...

    async def delete_updates_before(self, document_id: UUID, up_to_seq: int) -> None: ...

    async def get_next_seq(self, document_id: UUID) -> int: ...
