"""create document snapshots and updates tables

Revision ID: 83c9da859503
Revises: fd85a6cad744
Create Date: 2026-02-07 20:28:11.345993
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '83c9da859503'
down_revision: Union[str, None] = 'fd85a6cad744'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot', sa.LargeBinary(), nullable=False),
    sa.Column('state_vector', sa.LargeBinary(), nullable=False),
    sa.Column('update_seq', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_updates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('update_data', sa.LargeBinary(), nullable=False),
    sa.Column('update_seq', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_updates')
    op.drop_table('document_snapshots')
    # ### end Alembic commands ###
